/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "MQTT_Communication\protobuf\protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(iot_ServerToDeviceMessage, iot_ServerToDeviceMessage, AUTO)

PB_BIND(iot_ChangeDeviceModeCommand, iot_ChangeDeviceModeCommand, AUTO)

PB_BIND(iot_DeviceToServerMessage, iot_DeviceToServerMessage, 2)

PB_BIND(iot_DeviceTrackingDataMessage, iot_DeviceTrackingDataMessage, 2)

PB_BIND(iot_DeviceTrackingData, iot_DeviceTrackingData, 2)

PB_BIND(iot_FirmwareVersion, iot_FirmwareVersion, AUTO)

PB_BIND(iot_CellData, iot_CellData, AUTO)

PB_BIND(iot_WifiInfo, iot_WifiInfo, AUTO)
